Repository nhs-r-community/nhs-r-community, pull requests merged in 2024-06, with the labels that each got.

#61 Added blog to detail how to publish to GitHub
  blog/publish-on-github.qmd
Labels: content

#60 included_r_community_conference_2023_blog
  blog/nhs-r-community-conference-2023-my-experience-of-the-event.qmd
Labels: content

#62 Tidy links
  _quarto.yml
  index.qmd
Labels: bug

#64 A11y changes
  _quarto.yml
  books/posts/NHSR-way/index.qmd
  index.qmd
Labels: enhancement

#65 Added labels
  index.qmd
Labels: enhancement

#67 Added images to blogs
  blog/img/2023-nhsr-conference.jpg
  blog/img/screenshot-github-settings.PNG
  blog/nhs-r-community-conference-2023-my-experience-of-the-event.qmd
  blog/publish-on-github.qmd
Labels: content

#68 Add pareto chart
  blog/diverging-bar-charts-plotting-variance-with-ggplot2.qmd
  blog/pareto-chart-in-ggplot2.qmd
Labels: content

#71 Add sql blog
  blog/even-simpler-sql.qmd
  blog/simpler-sql-with-dplyr.qmd
Labels: bug

#72 Remove possibly redundant links which show up as alerts in WAVE check
  index.qmd
Labels: accessibility

#73 Revert "Remove possibly redundant links which show up as alerts in WAVE check"
  index.qmd
Labels: content
