Repository nhs-r-community/nhs-r-community, pull requests merged in 2024-11, with the labels that each got.

#235 Updated Google analytics tag from the original wordpress site
  _quarto.yml
Labels: enhancement

#236 adding info about using slack
  conference24.qmd
Labels: content, accessibility

#239 fix: remove phantom links around headings
  index.qmd
Labels: accessibility

#241 Fix focus visible issues on button styling
  assets/theme-dark.scss
  assets/theme-light.scss
  index.qmd
Labels: accessibility

#247 Changed speaker slots
  conference24.qmd
Labels: content

#253 Updated speaker on agenda
  conference24.qmd
Labels: content

#257 Added Coffee and Coding
  events.qmd
Labels: content

#260 Changed page to a header as the link is prefixed with a hash
  event_type-conferences.qmd
  events.qmd
Labels: enhancement

#261 Expanded on 404 page, moved contact from about folder and renamed to …
  404.qmd
  _quarto.yml
  contact.qmd
  events.qmd
Labels: enhancement, content
